apiVersion: apps/v1
kind: Deployment
metadata:
  name: hms-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hms-db
  template:
    metadata:
      labels:
        app: hms-db
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
        - name: MYSQL_DATABASE
          value: "hms_db"
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: db  # This name MUST be 'db' to match your Spring Boot URL
spec:
  selector:
    app: hms-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306